org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.workers.max=2
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.java.home=/home/wuying/.accio/accounts/1781857742/agents/DID-82AD6B-5682AD6BU1786883-9085-7C24FA/project/android/../tools/jdk21
